# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven New

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn clean install

    - name: Package
      run: mvn package
      
    - name: Unit Test
      run: mvn test
      
    - name: List current directory
      run: ls -la
      
    - name: target folder content
      run: |
        cd target
        ls -la
      
    - name: build & SonarQube analysis
      run: |
        mvn verify sonar:sonar -Dsonar.projectKey=testrepo1 -Dsonar.login=4c4e9b9c168315a700a1b32a90e04f61931a75ec -Dsonar.host.url=https://sonarcloud.io/
        sleep 60 
        
    - name: renaming-the-jar-and-backing-up-the-jar 
      run: |
        mkdir -p /opt/backup
        mv target/my-app-1.0-SNAPSHOT.jar target/1.0.${BUILD_NUMBER}.jar
        cp target/1.0.${BUILD_NUMBER}.jar /opt/backup/
  
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
       FILE: /opt/backup/1.0.${BUILD_NUMBER}.jar
       AWS_REGION: 'ap-south-1'
       S3_BUCKET: github-action1
       AWS_ACCESS_KEY_ID: AKIA5F24TNBK3HMM555K
       AWS_SECRET_ACCESS_KEY: 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    
        
        











